wormhole-foundation/wormhole-docs

- .CONTRIBUTING.md
Just noticed the spacing of some of the nested code elements was a little off, so I applied a quick fix and also my linter was catching trailing spaces, so those were removed
> fix spacing

- build/start-building/supported-networks/aptos.md
- build/start-building/supported-networks/evm.md
- learn/fundamentals/security.md
Minor text edits that I found while reading content.
> Minor text edits

- .github/workflows/check-mkdocs-build.yml
This PR should fix the broken builds
> fix the check-mkdocs-build workflow

- build/start-building/demos.md
- learn/messaging/cctp.md
This is a minor update and removes old references to the Connect SDK
> update connect sdk to typescript sdk

- build/start-building/testnet-faucets.md
> update faucet links

- .snippets/text/supported-networks.md
- build/start-building/testnet-faucets.md
Use more generic class name for chains lists (Supported Networks list and Faucets list)
Goes with mkdocs PR: https://github.com/papermoonio/wormhole-mkdocs/pull/50
> use more generic class name for chains lists

- build/contract-integrations/native-token-transfers/deployment-process/post-deployment.md
- learn/messaging/native-token-transfers/index.md
This PR adds next steps to push the users to start building after learning all things NTT. It also adds the demo integrations to the post deployment page.
> add next steps for the NTT docs

- build/applications/connect/features.md
- build/applications/queries/overview.md
- build/start-building/supported-networks/evm.md
- build/start-building/testnet-faucets.md
change the occurrence of klaytn to kaia in the docs.
> change occurrence of klaytn to kaia

- build/applications/connect/upgrade.md
Updated **Migration v1** page based on feedback received from Wormhole team.
> updated content based on feedback

- learn/governance/architecture.md
- learn/governance/overview.md
- tutorials/multigov/index.md
Noticed a few minor things on the MultiGov docs that need to be updated.
> minor updates

- build/contract-integrations/native-token-transfers/deployment-process/deploy-to-solana.md
> remove token2022 section from ntt docs

- build/contract-integrations/native-token-transfers/deployment-process/deploy-to-evm.md
> add setMinter example command to deploy to evm docs

- tutorials/messaging/index.md
> sui tutorial index

- infrastructure/spy/run-spy.md
> add log size limit flags to spy docs

- build/applications/wormhole-sdk/protocols-payloads.md
Noticed some minor things on the Protocols and Payloads page. Overall, really nice work on that page @martin0995!!
> minor fixes to protocols and payloads page

- build/contract-integrations/multigov/faq.md
> update multigov faq

- build/contract-integrations/multigov/faq.md
- build/contract-integrations/native-token-transfers/deployment-process/.pages
- build/contract-integrations/native-token-transfers/deployment-process/deploy-to-solana.md
- build/contract-integrations/native-token-transfers/deployment-process/index.md
- build/contract-integrations/native-token-transfers/deployment-process/troubleshooting.md
- variables.yml
> ntt troubleshooting

- variables.yml
> bump required solana cli version for ntt

- variables.yml
This updates the variables.yml file to use the latest version of the wormhole sdk. Resolves #194
> Update sdk version in the variables.yml

- variables.yml
Oops, we don't need the `v` in the version number, so this just removes it
> Update version variable

- learn/fundamentals/architecture.md
Added a more detailed explanation about the wormhole diagram flow
> add diagram explanation

- build/contract-integrations/native-token-transfers/deployment-process/deploy-to-solana.md
> add solana buffer account docs reference to sol ntt deployment

- build/applications/connect/configuration/configure-data.md
> minor connect fix

- llms.txt
- scripts/generate_llms.py
Simple PR to move a bit the variables so we can reuse the script a bit more easily
> Generalize Script

- build/contract-integrations/native-token-transfers/deployment-process/troubleshooting.md
- llms.txt
- variables.yml
> bump required solana ntt cli version

- variables.yml
This updates the SDK version to v1.9.0. There were no other updates in this release that impacted the docs
> Bump SDK version to 1.9.0

- .github/workflows/check-llms.yml
- llms.txt
- scripts/generate_llms.py
This PR generalizes the script even more and fixes some bugs.
> Fixes LLMS Script

- build/contract-integrations/wormhole-relayers.md
- llms.txt
> add sendToEvm comment for consistency level optimizations

- learn/messaging/wormhole-settlements/overview.md
- llms.txt
> add link to settlements

- variables.yml
- Update sdk version to `v.1.11.1`.
- Resolves #272
> sdk update to v.1.11.1

- learn/messaging/native-token-transfers/overview.md
> Update overview.md to fix broken link to solana ntt deployment guide

- build/contract-integrations/multigov/deploy-to-evm.md
- build/start-building/use-cases.md
- llms.txt
> Multigov repo and change emoji

- build/transfers/.pages
- build/transfers/token-bridge.md
adds token bridge build page in the new ai and fixes links
> Bring token bridge build into new ia

- learn/transfers/settlement/architecture.md
- llms.txt
Resolve merge conflicts for new-product-ia branch
> Resolve merge conflicts for new-product-ia branch

- variables.yml
Update sdk to the latest version `1.14.1`.
Resolves #339 
Related to: https://github.com/papermoonio/wormhole-mkdocs/pull/209
> update sdk to latest version

- variables.yml
> bump cli version again

- variables.yml
Bump to new sdk version `1.14.2`
Closes #348 
Related to https://github.com/papermoonio/wormhole-mkdocs/pull/211
> update sdk version

- build/start-building/index.md
- llms-full.txt
added missing links and deleted create your first transfer part because there was already a section about it
> fix start building page

- variables.yml
Update wormhole version to `2.33.0`.
Resolves #352
> update wormhole version to 2.33.0

- variables.yml
Update the sdk to the latest version `1.16.1`
Resolves #373 
Related to: https://github.com/papermoonio/wormhole-mkdocs/pull/227
> Update SDK to the latest version

- variables.yml
Update SDK to the latest version `1.17.0`
- Resolves #385 
- Related to: https://github.com/papermoonio/wormhole-mkdocs/pull/229
> Update SDK to version 1.17.0

- build/start-building/products.md
- llms-files/llms-basics.txt
- llms-files/llms-connect.txt
- llms-files/llms-multigov.txt
- llms-files/llms-ntt.txt
- llms-files/llms-queries.txt
- llms-files/llms-relayers.txt
- llms-files/llms-settlement.txt
- llms-files/llms-solidity-sdk.txt
- llms-files/llms-token-bridge.txt
- llms-files/llms-transfer.txt
- llms-files/llms-typescript-sdk.txt
- llms-full.txt
remove connect from product comparison table as requested, later we'll create a connect vs ts SDK comparison
> remove Connect from product comparison table

- build/transfers/connect/features.md
- build/transfers/native-token-transfers/deployment-process/deploy-to-solana.md
- llms-files/llms-connect.txt
- llms-files/llms-ntt.txt
- llms-files/llms-transfer.txt
- llms-full.txt
> Staked rpc comment & feature matrix adjustment

- products/messaging/overview.md
- products/multigov/overview.md
- products/queries/overview.md
minor fixes to links in use cases to be consistent and direct to overview pages
direct to get started pages only for the product of the page we're on
> link adjustments

- .snippets/code/build/core-messaging/core-contracts/attestToken.sol
- .snippets/code/build/core-messaging/core-contracts/transferTokens.sol
- .snippets/code/build/core-messaging/core-contracts/transferTokensWithPayload.sol
- .snippets/code/build/transfers/cctp/CircleIntegration.sol
- build/transfers/token-bridge.md
- llms-files/llms-token-bridge.txt
- llms-files/llms-transfer.txt
- llms-full.txt
> Message fee

- build/transfers/token-bridge.md
- llms-files/llms-token-bridge.txt
- llms-files/llms-transfer.txt
- llms-full.txt
This PR just rolls back the latest changes to token bridge
> rollback example changes

- products/token-bridge/concepts/payload-structure.md
Toke Bridge Payload Structure page
> Token Bridge Payload Structure

- .snippets/text/products/reference/ntt/overview/ntt-timeline.json
- products/native-token-transfers/overview.md
> Overview - Native Token Tranfers

- llms-files/llms-ntt.txt
- llms-files/llms-queries.txt
- llms-files/llms-transfer.txt
- llms-full.txt
- products/native-token-transfers/guides/deploy-to-evm.md
- products/queries/get-started.md
This PR fixes a few more 404s. There are still some 404s revolving around the Solidity SDK page changes. But the whole guide is outdated at this point, so we'll get that fixed up separately.
> Fix a few more 404s

- build/transfers/native-token-transfers/deployment-process/deploy-to-solana.md
- llms-files/llms-ntt.txt
- llms-files/llms-transfer.txt
- llms-full.txt
> adjust solana buffer accounts comment

- llms-files/llms-ntt.txt
- llms-files/llms-transfer.txt
- llms-full.txt
- products/native-token-transfers/guides/deploy-to-solana.md
> clarify ntt solana hub & spoke chain comment

- llms-files/llms-cctp.txt
- llms-files/llms-ntt.txt
- llms-files/llms-transfer.txt
- llms-full.txt
- products/native-token-transfers/guides/deploy-to-solana.md
- products/native-token-transfers/guides/post-deployment.md
> adjust the solana ntt deployment docs to the new cli commands for setting the mint authority + demo-ntt-connect comment from vite to nextjs
