wormhole-foundation/wormhole-docs

- .snippets/text/supported-networks.md
This PR updates the styling of the Supported Networks snippet. Instead of a table, a grid is now used (similarly to the TestNet faucets page).
> updated supported networks styling

- build/toolkit/.pages
> Fix toolkit link to the sdk

- tutorials/messaging/cross-chain-contracts.md
Based on WH feedback, I added a link to the [reference page](https://wormhole.com/docs/build/reference/) in the tutorial, where users can check the complete list of contract addresses.
> contract addresses reference

- tutorials/messaging/cross-chain-contracts.md
- tutorials/messaging/cross-chain-token-contracts.md
Updated links for tutorials. Now, tutorials are pointing to Wormhole's GitHub account.
> Updated links pointing at Wormhole's github

- build/applications/connect/configuration.md
- build/applications/connect/upgrade.md
I have updated code snippets from the Connect Configuration and Migration pages. The `WormholeConnect` component was imported incorrectly.
> updated code snippets in connect configurations

- build/contract-integrations/native-token-transfers/deployment-process/deploy-to-evm.md
- build/contract-integrations/native-token-transfers/deployment-process/deploy-to-solana.md
> add clarifying solana priority fee flag & ntt manager address notes

- build/contract-integrations/native-token-transfers/deployment-process/deploy-to-solana.md
I tried deploying the NTT program for Solana following the documentation and encountered a specific Anchor version error (see the image below). I have added a relevant note to the docs.
> added relevant comment related to Solana deployment version

- tutorials/messaging/sui-connect.md
Added resources and conclusion to connect sui tutorial
> connect tutorial adjustement

- build/contract-integrations/native-token-transfers/deployment-process/deploy-to-solana.md
The [NTT Solana Deployment Page](https://wormhole.com/docs/build/contract-integrations/native-token-transfers/deployment-process/deploy-to-solana/) needs to be clarified. When following the steps, the page refers to the same thing with a different name, generating confusion.
Example:
- The newly created token address is referred to as INSERT_YOUR_SPL_TOKEN and INSERT_TOKEN_ADDRESS
> terms standardization

- build/applications/connect/configuration.md
- build/applications/connect/routes.md
- build/applications/connect/upgrade.md
- build/contract-integrations/native-token-transfers/deployment-process/deploy-to-evm.md
- build/contract-integrations/native-token-transfers/deployment-process/installation.md
- build/contract-integrations/native-token-transfers/faqs.md
wormhole wants to rename the repo example-native-token-transfers to native-token-transfers so dropping the example-
this pr updates the links that point to that repo
> update ntt links

- .snippets/code/build/applications/wormhole-sdk/custom-route.ts
- build/applications/wormhole-sdk.md
This adds a Routes as Plugins (custom routes) section to the TypeScript SDK docs. It also points to the NTT SDK as an example.
> add wormhole-sdk custom routes section

- learn/fundamentals/glossary.md
Removed old terms from the glossary.
> removed old terms from glossary

- tutorials/index.md
Updated duplicate title in the Tutorial's index page.
> updated title to multigov

- learn/infrastructure/vaas.md
The VAA fields for payload 3 (token transfer with message) transfers is documented incorrectly. The correct behaviour can be seen [here](https://github.com/wormhole-foundation/wormhole/blob/063e04f859adc9ced10b22892c6a638defbf1f23/ethereum/contracts/bridge/Bridge.sol#L728). I have updated the docs to reflect the real VAA structure.
> Fix VAA fields for payload 3 types

- build/contract-integrations/native-token-transfers/deployment-process/deploy-to-solana.md
> remove misleading comment about ntt program id in ntt solana deployment docs

- build/contract-integrations/native-token-transfers/deployment-process/troubleshooting.md
> add dockerfile & docker-compose.yml for a basic ntt cli setup

- tutorials/by-product/contract-integrations/cross-chain-contracts.md
Added missing link to GitHub for the messaging tutorial.
> add link to demo on github for tutorial

- build/contract-integrations/native-token-transfers/faqs.md
remove question about IsSpecializedRelayer from faq
> remove question from faq

- .github/scripts/check_repositories.py
- .github/scripts/create_issues.py
- .github/workflows/check-repositories.yaml
- variables.yml
This PR adds a new GitHub Action that automatically checks for outdated repository versions in our documentation. The action reads repository information from variables.yml, compares documented versions with the latest releases on GitHub, and creates issues for any outdated repositories.
It will specifically be used to create an issue anytime a new version of the wormhole sdk is released so we can update chain and contract details.
> add check repositories action

- build/contract-integrations/native-token-transfers/deployment-process/deploy-to-evm.md
- build/contract-integrations/native-token-transfers/deployment-process/deploy-to-solana.md
Added at the end of Native Token Transfers EVM Deployment for evm and solana sections a short sentence with a link to "Post Deployment"
> added links to ntt post deployment

- build/contract-integrations/index.md
Added cctp index card which was missing in the build > contract integrations index page
> add cctp index card

- tutorials/messaging/loyalty-app.md
An issue found in the sui workshop example
> package naming inconsistency sample fix (@ilarae)

- tutorials/by-product/index.md
We removed the NTT section temporarily because we don't have any NTT tutorials quite yet. The tutorial that was under NTT was actually for wrapped assets, so that was moved to the Multichain Assets section. So this PR updates the Tutorials by Product index page to reflect these changes
> Replace NTT card with Multichain Assets on the Tutorials by Product index page

- learn/messaging/native-token-transfers/overview.md
Added explanations in the overview page that ntt doesn't use wrappers 
also checked that we use the term hub&spoke - not lock and mint - and we were already doing that in all pages of learn and build
> add ntt no wrappers explanation

- build/applications/queries/use-queries.md
- learn/messaging/cctp.md
- llms.txt
This audit was smaller than last month's; it addresses only two broken links and a minor word change from 'smart contract' to 'library.'
> Semrush Audit February

- build/reference/index.md
- infrastructure/relayers/index.md
- infrastructure/spy/index.md
- llms.txt
This PR just converts the few remaining material icons on the index pages to octicons, so they have the same properties across the board. For example, material applies a different viewbox size to their icons and octicons doesn't
This kinda goes with this mkdocs PR: https://github.com/papermoonio/wormhole-mkdocs/pull/156
> Update index page icons for consistency

- build/transfers/connect/configuration-v0.md
- build/transfers/native-token-transfers/faqs.md
- llms.txt
I created a new pull request for the March Semrush report because the previous one had too many merge conflicts. 
https://github.com/wormhole-foundation/wormhole-docs/pull/296
**this is the original description (addresses the same issues)**
I updated a GitHub link and removed the colon from a title because it created a conflict that prevented the description from appearing, resulting in an error in the SEMrush report.
> Semrush march fix

- build/start-building/products.md
- llms.txt
Replaces #297. 
Updated the Token Transfers with Message Payloads row to reflect that NTT supports this, per this https://github.com/wormhole-foundation/wormhole-docs/pull/283#discussion_r1995328865. I also ran the formatter on the table which is why it looks like the whole thing was changed
> update product table to show ntt supports transfers with messages

- build/transfers/native-token-transfers/deployment-process/deploy-to-solana.md
- llms.txt
- scripts/generate_llms.py
> remove ntt devnet initialization, as for Solana devnet also the ntt testnet config is working

- learn/infrastructure/architecture.md
- llms.txt
Refreshes the learn/infra/architecture overview page by:
- minor copy changes
- adds Next Steps section
- [x ] **Required** - I have added a label to this PR 🏷️
- [ x] **Required** - I have run my changes through Grammarly
- [ n/a] If pages have been moved, I have created redirects in the `wormhole-mkdocs` repo
> refresh infra architecture, updates llms

- variables.yml
- Small fix to wormhole version in the variables file. Version was incorrectly higher than the current one.
- Resolves #318 
- Current version `2.31.0` -> correct version `2.30.0`
> downgrade wh version

- llms-full.txt
- tutorials/by-product/index.md
- tutorials/index.md
This PR adds a couple of generic headers for now. Since we're reworking the tutorials section, I didn't want to spend too much time on this. I just want to ensure that we're not showing empty TOCs anymore: https://wormhole.com/docs/tutorials/by-product/.
Additionally, as we've been improving other index pages (such as the root-level Build and Learn index pages, which contain multiple sections), restoring the TOC on these pages enhances navigation.
This PR goes with: https://github.com/papermoonio/wormhole-mkdocs/pull/203
> add generic headers

- build/start-building/index.md
This restores the start building index page to what it was before.
> revert start building index page

- llms-full.txt
- tutorials/solidity-sdk/cross-chain-token-contracts.md
- tutorials/typescript-sdk/tokens-via-token-bridge.md
- tutorials/typescript-sdk/usdc-via-cctp.md
This PR adds a step to add a .gitignore to these tutorials. If the user starts from the demo repo README of these tutorials, they will clone the repo and have a .gitignore. However, if they start from the tutorial, there is no mention of cloning the repo and they start a fresh project. These instructions lacked use of .gitignore which could cause exposure of private keys. 
This is a temp fix and part of a larger initiative to remove the use of plain-text private keys in .env files in guides and tutorials. 
This PR is only intended to address these specific issues. If you wish to make any additional changes to these pages, please open a ticket. 
- [ x] **Required** - I have added a label to this PR 🏷️
- [x ] **Required** - I have run my changes through Grammarly
- [n/a ] If pages have been …
> Add gitignore step

- .snippets/code/build/core-messaging/core-contracts/attestToken.sol
- .snippets/code/build/transfers/cctp/CircleIntegration.sol
- build/transfers/token-bridge.md
- llms-files/llms-token-bridge.txt
- llms-files/llms-transfer.txt
- llms-full.txt
> adjust tokenbridge function & llms generation
